import{STORAGE_KEY,DAY,dateKey,emptyState,normalizeAnswer,schedule,statusOf,validateState,makeQueue,makeChoices,shouldShowStarPrompt}from './core.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',book:'M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3ZM12 6v15',star:'m12 3 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',chart:'M4 20V10m8 10V4m8 16v-7M2 22h20',settings:'M4 6h16M4 12h16M4 18h16M8 3v6m8 0v6M10 15v6'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]}"/></svg>`;
let data,words,byId,years,state,view='home',filterYear='all',search='',filterStatus='all',listPage=1,listKind='favorites',revealed=false,feedback=null,choiceQuestion=null,saved=true,saveError='',toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3800);}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));saved=true;saveError='';}catch{saved=false;saveError='浏览器未能保存进度。请到学习设置导出备份，避免关闭后丢失。';toast(saveError);}updateSaveIndicator();}
function updateSaveIndicator(){const el=$('#save-label');if(el)el.textContent=saved?'进度已保存在本机':'保存失败 · 请导出备份';const b=$('#save-error');if(b){b.textContent=saveError;b.classList.toggle('hidden',saved);}}
const mastered=ws=>ws.filter(w=>statusOf(state.progress[w.id])==='mastered').length;
const learned=ws=>ws.filter(w=>state.progress[w.id]).length;
const due=ws=>ws.filter(w=>state.progress[w.id]?.due<=Date.now()).length;
function streak(){let n=0,d=new Date();if(!state.history[dateKey()]?.reviews)d.setDate(d.getDate()-1);while(state.history[dateKey(d)]?.reviews){n++;d.setDate(d.getDate()-1);}return n;}
function shell(body){const nav=[['home','home','今日学习'],['library','book','年份词库'],['favorites','star','生词与错词'],['stats','chart','学习统计'],['settings','settings','学习设置']];$('#app').innerHTML=`<div id="save-error" class="save-error ${saved?'hidden':''}">${esc(saveError)}</div><div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">W</div><div><strong>词序</strong><small>WORDS IN TIME</small></div></div><nav class="nav" aria-label="主导航">${nav.map(([id,ic,t])=>`<button data-nav="${id}" class="${view===id||(view==='study'&&id==='home')?'active':''}" ${view===id?'aria-current="page"':''}>${icon(ic)}${t}</button>`).join('')}</nav><div class="side-bottom"><span class="dot"></span><span id="save-label">${saved?'进度已保存在本机':'保存失败 · 请导出备份'}</span><br>真题词汇 · ${years[0]}—${years.at(-1)}<br>每天一点，慢慢记牢。</div></aside><main class="main"><div class="topline"><span>我的学习空间 / ${view==='study'?'专注学习':nav.find(n=>n[0]===view)?.[2]||'今日学习'}</span><span>${new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span></div>${body}</main></div>`;}
function intro(title,sub,action=''){return `<div class="intro"><div><h1>${title}</h1><p class="muted">${sub}</p></div>${action}</div>`;}
function statItems(items){return `<div class="stats">${items.map(([label,num,unit])=>`<div class="stat"><div class="stat-label">${label}</div><strong>${num}</strong><small>${unit}</small></div>`).join('')}</div>`;}
function week(){return `<div class="week">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return `<div class="day ${state.history[dateKey(d)]?.reviews?'done':''} ${i===6?'today':''}"><i>${state.history[dateKey(d)]?.reviews?'✓':d.getDate()}</i>${['日','一','二','三','四','五','六'][d.getDay()]}</div>`;}).join('')}</div>`;}
function yearCards(){return `<div class="year-grid">${years.map(y=>{const w=words.filter(w=>w.year===y),n=learned(w),pct=Math.round(n/w.length*100);return `<button class="year-card" data-year="${y}"><span class="year">${y}<span class="badge" style="float:right;margin-top:6px">英语一</span></span><p>${w.length} 个词条 · ${new Set(w.flatMap(x=>x.sources.map(s=>s.section))).size} 个题型单元</p><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="year-bottom"><span>${n?'已学 '+n+' 词':'尚未开始'}</span><span>${pct}% ↗</span></div></button>`;}).join('')}</div>`;}
function home(){const t=state.history[dateKey()]?.ids.length||0,g=state.settings.goal,active=state.session&&state.session.index<state.session.queue.length;return intro('把今天的单词，记牢。','从真题出发，让每一次复习都有积累。',`<button data-nav="library">浏览全部词库 ↗</button>`)+statItems([['累计学习',learned(words),'词'],['待复习',due(words),'词'],['已经掌握',mastered(words),'词'],['连续学习',streak(),'天']])+`<div class="dashboard-grid"><section class="panel plan"><div class="eyebrow">TODAY’S PRACTICE</div><h2>${active?'接着上次，继续学。':'今天，从 '+state.settings.batch+' 个词开始。'}</h2><p>${active?'已完成 '+state.session.index+' / '+state.session.queue.length+' 个词，进度已为你保留。':due(words)?'有 '+due(words)+' 个词到了复习时间。先巩固，再认识新单词。':'选择熟悉的年份，或者跟着今日计划开始。'}</p><div class="plan-footer"><button class="primary" ${active?'data-resume':'data-start="all"'}>${active?'继续学习':'开始今日学习'} &nbsp; →</button><button class="text-button" data-start="due">只复习到期词</button></div></section><section class="panel"><div class="section-title"><h2>每日目标</h2><button class="text-button" data-nav="settings">调整</button></div><div class="goal-row"><span>今日已学 <b>${t}</b> 词</span><span class="muted">${Math.round(t/g*100)}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,t/g*100)}%"></div></div><div class="muted" style="margin-top:10px;font-size:11px">${t>=g?'今日目标已完成，做得不错。':'距离 '+g+' 词的目标，还差 '+(g-t)+' 词。'}</div>${week()}</section></div><div class="section-title"><h2>按年份学习</h2><span class="muted">${years.length} 个年份 · ${words.length.toLocaleString()} 个词条</span></div>${yearCards()}`;}
function yearOptions(){return `<option value="all">全部年份</option>${years.map(y=>`<option value="${y}" ${String(y)===filterYear?'selected':''}>${y} 年</option>`).join('')}`;}
function library(favorites=false){let pool=words.filter(w=>(filterYear==='all'||String(w.year)===filterYear)&&(!search||`${w.word} ${w.meaning}`.toLowerCase().includes(search.toLowerCase()))&&(filterStatus==='all'||statusOf(state.progress[w.id])===filterStatus));if(favorites)pool=pool.filter(w=>listKind==='favorites'?state.favorites.includes(w.id):(state.progress[w.id]?.lapses||0)>0);const max=Math.max(1,Math.ceil(pool.length/40));listPage=Math.min(max,listPage);return intro(favorites?'留给自己，多复习一次。':filterYear==='all'?'每一年，都是一个起点。':filterYear+' 年 · 真题词库',favorites?'收藏容易忘的词，也看看练习中出过错的词。':'按年份筛选，查看释义和出处，随时开始学习。',`<button class="primary" data-start="${favorites?listKind:'all'}">学习当前词库 →</button>`)+(favorites?`<div class="mode-tabs" style="width:fit-content"><button data-list-kind="favorites" class="${listKind==='favorites'?'active':''}">我的生词 ${state.favorites.length}</button><button data-list-kind="mistakes" class="${listKind==='mistakes'?'active':''}">错词回顾 ${words.filter(w=>state.progress[w.id]?.lapses>0).length}</button></div>`:'')+`<div class="toolbar"><input id="search" type="search" aria-label="搜索单词或中文释义" placeholder="搜索单词或中文释义" value="${esc(search)}"><select id="year-filter" aria-label="筛选年份">${yearOptions()}</select><select id="status-filter" aria-label="筛选掌握状态">${[['all','全部状态'],['new','未学习'],['due','待复习'],['learning','学习中'],['mastered','已掌握']].map(([v,t])=>`<option value="${v}" ${filterStatus===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="section-title"><span class="muted">共 ${pool.length} 个词条</span><span class="muted">☆ 收藏 · ♪ 发音</span></div><div class="word-list">${pool.slice((listPage-1)*40,listPage*40).map(w=>`<div class="word-row"><div><div class="word-en">${esc(w.word)}</div><span class="word-meta">${w.year} · ${esc(w.sources.map(s=>s.section).filter((x,i,a)=>a.indexOf(x)===i).join(' / '))}</span></div><div class="word-meaning">${esc(w.pos)} ${esc(w.meaning)}${w.review?'<span class="badge">待核对</span>':''}</div><span class="badge">${{new:'未学习',due:'待复习',learning:'学习中',mastered:'已掌握'}[statusOf(state.progress[w.id])]}</span><div class="row-actions"><button class="icon-button" data-speak="${w.id}" aria-label="朗读 ${esc(w.word)}">♪</button><button class="icon-button ${state.favorites.includes(w.id)?'favorite':''}" data-favorite="${w.id}" aria-label="${state.favorites.includes(w.id)?'取消收藏':'收藏'} ${esc(w.word)}" aria-pressed="${state.favorites.includes(w.id)}">${state.favorites.includes(w.id)?'★':'☆'}</button></div></div>`).join('')||'<div class="empty">这里还没有词条。<br>换个筛选条件，或去词库收藏想记住的词。</div>'}</div><div class="pagination"><button data-page="-1" ${listPage<=1?'disabled':''}>上一页</button><span>${listPage} / ${max}</span><button data-page="1" ${listPage>=max?'disabled':''}>下一页</button></div>`;}
function choiceCard(w){
 const options=choiceQuestion.options;
 return `<h2 class="card-word choice-word">${esc(w.word)}</h2><button class="sound-button" data-speak="${w.id}">♪ 听发音</button><p class="card-hint choice-hint">请选择最贴近的中文释义</p><div class="choice-options" role="group" aria-label="${esc(w.word)} 的中文释义">${options.map((option,i)=>`<button class="choice-option ${feedback?(option.id===w.id?'correct':option.id===feedback.choice?'incorrect':''):''}" data-choice="${option.id}" ${feedback?'disabled':''}><span class="choice-index">${'ABC'[i]}</span><span>${esc(option.meaning)}</span></button>`).join('')}</div>${feedback?`<p class="feedback ${feedback.correct?'':'wrong'}" role="status">${feedback.correct?'选对了！':'选错了，绿色选项是正确释义。'}</p>`:''}<div class="card-bottom">${feedback?'<button class="primary" id="choice-next" data-next>下一个 →</button>':''}</div>`;
}
function study(){
 const s=state.session;
 if(!s||s.index>=s.queue.length)return intro('这一组，完成了。','学习进度已经保存，下次会优先安排到期复习。')+`<section class="panel empty"><h2>${s?.answered||0} 次练习 · ${s?.correct||0} 次记住</h2><p>短暂休息一下，也可以继续下一组。</p><button class="primary" data-start="all">再学一组</button> <button data-nav="home">回到首页</button></section>`;
 const w=byId.get(s.queue[s.index]);
 if(s.mode==='choice'&&choiceQuestion?.id!==w.id)choiceQuestion={id:w.id,options:makeChoices(words,w)};
 const card=s.mode==='cards'?`<h2 class="card-word">${esc(w.word)}</h2><button class="sound-button" data-speak="${w.id}">♪ 听发音</button>${revealed?`<div class="card-answer">${esc(w.pos)} ${esc(w.meaning)}</div>`:'<p class="card-hint">先想一想，这个词是什么意思？</p>'}<div class="card-bottom">${revealed?'':'<button class="primary" data-reveal>查看释义 &nbsp; 空格</button>'}</div>`:s.mode==='choice'?choiceCard(w):`<h2 class="card-word" style="font-family:inherit;font-size:23px;margin-top:42px">${esc(w.meaning)}</h2><div class="muted">${esc(w.pos)||'单词 / 短语'}</div><form class="spell-form" id="spell-form"><input id="answer" aria-label="输入英文答案" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="输入英文…" ${feedback?'disabled':''}><button class="primary" ${feedback?'disabled':''}>检查</button></form>${feedback?`<div class="feedback ${feedback.correct?'':'wrong'}">${feedback.correct?'拼对了！':'正确答案：'+esc(w.word)}</div><div class="muted">${esc(w.meaning)}</div><button class="text-button" data-speak="${w.id}">♪ 听发音</button>`:'<p class="card-hint">按 Enter 检查答案，短语也请完整输入。</p>'}<div class="card-bottom">${feedback?'<button class="primary" data-next>下一个 →</button>':'<button class="text-button" data-dont-know>暂时想不起来</button>'}</div>`;
 const shortcuts=s.mode==='cards'?'空格 翻卡 · 1 没记住 · 2 模糊 · 3 记住 · P 发音':s.mode==='choice'?'1 / 2 / 3 选中文 · P 发音':'Enter 检查 / 继续 · P 发音';
 return intro('专注眼前这一个。',s.year==='all'?'跨年份学习 · 先复习，再学新词':s.year+' 年真题词汇',`<button data-nav="home">退出并保存</button>`)+`<div class="study-controls"><div class="mode-tabs" role="group" aria-label="学习模式">${[['cards','单词卡'],['choice','看英文选中文'],['spell','看义拼写']].map(([id,t])=>`<button data-mode="${id}" class="${s.mode===id?'active':''}">${t}</button>`).join('')}</div><div class="session-progress"><span>${s.index+1} / ${s.queue.length}</span><div class="progress-track"><div class="progress-fill" style="width:${s.index/s.queue.length*100}%"></div></div></div></div><section class="flashcard"><div class="card-top"><span>${w.year} · ${esc(w.sources[0].section)} ${w.review?'· 待核对':''}</span><button class="icon-button ${state.favorites.includes(w.id)?'favorite':''}" data-favorite="${w.id}" aria-label="收藏当前词" aria-pressed="${state.favorites.includes(w.id)}">${state.favorites.includes(w.id)?'★':'☆'}</button></div>${card}</section>${s.mode==='cards'&&revealed?`<div class="grades"><button class="danger" data-grade="again">没记住<small>10 分钟后复习</small></button><button data-grade="hard">有点模糊<small>稍后巩固</small></button><button class="primary" data-grade="good">记住了<small>延长复习间隔</small></button></div>`:''}<p class="shortcuts">${shortcuts}</p>`;
}
function stats(){const h=Object.values(state.history),total=h.reduce((s,x)=>s+x.reviews,0),correct=h.reduce((s,x)=>s+x.correct,0),bars=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()-13+i);return {label:`${d.getMonth()+1}/${d.getDate()}`,n:state.history[dateKey(d)]?.reviews||0};}),max=Math.max(1,...bars.map(b=>b.n));return intro('每一次重复，都算数。','在这里看看，你已经走了多远。')+statItems([['累计练习',total,'次'],['记住比例',total?Math.round(correct/total*100)+'%':'—',''],['连续学习',streak(),'天'],['学习天数',h.filter(x=>x.reviews>0).length,'天']])+`<div class="panel"><div class="section-title"><h2>近两周练习</h2><span class="muted">每次作答计 1 次</span></div><div class="chart">${bars.map(b=>`<div class="bar" style="height:${Math.max(2,b.n/max*100)}%"><b>${b.n||''}</b><span>${b.label}</span></div>`).join('')}</div></div><div class="panel" style="margin-top:23px"><h2>各年份进度</h2>${years.map(y=>{const ws=words.filter(w=>w.year===y);return `<div class="report-row"><span>${y} 年</span><span>${learned(ws)} / ${ws.length} 已学 · ${mastered(ws)} 已掌握</span></div>`;}).join('')}</div><p class="footer-note">“已掌握”表示复习间隔达到 21 天；“记住比例”统计单词卡选择“记住了”、中文三选一答对及拼写正确的练习。相同词条当天多次作答，只计入每日目标一次。</p>`;}
function settings(){const s=state.settings;return intro('按你的节奏来。','设置学习目标，保管好每一天的进步。')+`<div class="settings-grid"><section class="panel"><h2>学习偏好</h2><form id="settings-form"><label class="field">每日目标<input type="number" name="goal" min="1" max="500" required value="${s.goal}"><small>每天学习的不同词条数，包含复习。</small></label><label class="field">每组词数<select name="batch">${[10,20,30,50,100].map(n=>`<option ${s.batch===n?'selected':''}>${n}</option>`).join('')}</select></label><label class="field">发音口音<select name="voice"><option value="en-US" ${s.voice==='en-US'?'selected':''}>美式英语</option><option value="en-GB" ${s.voice==='en-GB'?'selected':''}>英式英语</option></select></label><label class="field">朗读速度<select name="rate">${[[0.65,'慢速'],[0.85,'适中'],[1,'正常']].map(([v,t])=>`<option value="${v}" ${s.rate===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="checkbox"><input type="checkbox" name="shuffle" ${s.shuffle?'checked':''}>随机排列同优先级的单词</label><div class="settings-actions"><button class="primary">保存设置</button></div></form></section><section class="panel"><h2>进度与备份</h2><p class="muted">进度自动保存在当前设备的浏览器中。换手机、换浏览器或清理网站数据前，请导出一份备份。</p><div class="settings-actions"><button class="primary" data-export>导出学习备份</button><button data-import>导入备份</button><input id="import-file" type="file" accept="application/json,.json" hidden></div><div class="notice">GitHub Pages 静态版不提供账号云同步。无痕模式的进度可能在退出后清除，备份文件可以在另一台设备导入。</div><h3 style="margin-top:28px">重新开始</h3><p class="muted">清除学习进度、收藏和统计。操作前建议先导出备份。</p><button class="danger" data-reset>清除所有学习记录</button></section></div>`;}
function render(){shell(view==='home'?home():view==='library'?library():view==='favorites'?library(true):view==='study'?study():view==='stats'?stats():settings());}
function maybeStarPrompt(){if(!shouldShowStarPrompt(state,learned(words)))return;state.starPromptSeen=true;save();$('#star-dialog').showModal();}
function navigate(next){view=next;if(next!=='study'){revealed=false;feedback=null;}render();window.scrollTo({top:0});}
function start(kind){const year=view==='home'?'all':filterYear;const queue=makeQueue(words,state,{year,kind});if(!queue.length){toast(kind==='due'?'目前没有到期词，稍后再来复习。':'当前范围没有可学习的词。可在生词本练习收藏词，或选择其他年份。');return;}state.session={queue,index:0,year,mode:'cards',correct:0,answered:0};save();revealed=false;feedback=null;choiceQuestion=null;view='study';render();window.scrollTo({top:0});}
function record(grade){const s=state.session,w=byId.get(s.queue[s.index]);state.progress[w.id]=schedule(state.progress[w.id],grade);const h=state.history[dateKey()]||{reviews:0,correct:0,ids:[]};h.reviews++;if(grade==='good'){h.correct++;s.correct++;}if(!h.ids.includes(w.id))h.ids.push(w.id);state.history[dateKey()]=h;s.answered++;}
function next(){state.session.index++;revealed=false;feedback=null;choiceQuestion=null;save();render();maybeStarPrompt();if(state.session.mode==='spell')$('#answer')?.focus();}
function checkAnswer(value){if(feedback)return;const w=byId.get(state.session.queue[state.session.index]);feedback={correct:normalizeAnswer(value)===normalizeAnswer(w.word)};render();}
function speak(id){if(!('speechSynthesis'in window)){toast('此浏览器不支持发音，请换用 Chrome、Edge 或 Safari。');return;}const w=byId.get(id);if(!w)return;const u=new SpeechSynthesisUtterance(w.word.replace(/\.{2,}/g,' '));u.lang=state.settings.voice;u.rate=state.settings.rate;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang===u.lang)||voices.find(v=>v.lang.startsWith('en'))||null;u.onerror=()=>toast('暂时无法播放发音，请检查设备语音设置或网络。');speechSynthesis.cancel();speechSynthesis.speak(u);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.nav){navigate(d.nav);return;}if(d.year){filterYear=d.year;search='';filterStatus='all';listPage=1;navigate('library');return;}if('start'in d){start(d.start);return;}if('resume'in d){view='study';render();return;}if(d.favorite){const i=state.favorites.indexOf(d.favorite);if(i<0)state.favorites.push(d.favorite);else state.favorites.splice(i,1);save();render();return;}if(d.speak){speak(d.speak);return;}if('reveal'in d){revealed=true;render();return;}if(d.grade&&revealed){record(d.grade);next();return;}if(d.mode){if(feedback){record(feedback.correct?'good':'again');next();}state.session.mode=d.mode;revealed=false;feedback=null;save();render();if(d.mode==='spell')$('#answer')?.focus();return;}if(d.choice){if(feedback||state.session?.mode!=='choice')return;const w=byId.get(state.session.queue[state.session.index]);if(!choiceQuestion?.options.some(option=>option.id===d.choice))return;feedback={correct:d.choice===w.id,choice:d.choice};render();$('#choice-next')?.focus();return;}if('next'in d){if(feedback){record(feedback.correct?'good':'again');next();}return;}if('dontKnow'in d){checkAnswer('');return;}if(d.listKind){listKind=d.listKind;listPage=1;render();return;}if(d.page){listPage+=Number(d.page);render();window.scrollTo({top:0});return;}if('export'in d){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`词序-学习备份-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return;}if('import'in d){$('#import-file').click();return;}if('reset'in d){if(confirm('清除本机全部学习记录、收藏和统计？此操作不能撤销，请先导出备份。')){state=emptyState();save();render();toast('学习记录已清除。');}return;}});
document.addEventListener('change',async e=>{if(e.target.id==='year-filter'){filterYear=e.target.value;listPage=1;render();}if(e.target.id==='status-filter'){filterStatus=e.target.value;listPage=1;render();}if(e.target.id==='import-file'){const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('备份文件过大。');const incoming=validateState(JSON.parse(await file.text()),new Set(byId.keys()));if(!confirm(`将用备份替换当前进度（${Object.keys(incoming.progress).length} 个已学词）。继续吗？`))return;state=incoming;save();render();maybeStarPrompt();toast('备份已导入。');}catch(err){toast(err.message||'无法读取备份。');}}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;listPage=1;const cursor=e.target.selectionStart;render();$('#search').focus();try{$('#search').setSelectionRange(cursor,cursor);}catch{}}});
document.addEventListener('submit',e=>{if(e.target.id==='spell-form'){e.preventDefault();checkAnswer($('#answer').value);}if(e.target.id==='settings-form'){e.preventDefault();const f=new FormData(e.target);state.settings={goal:Number(f.get('goal')),batch:Number(f.get('batch')),voice:f.get('voice'),rate:Number(f.get('rate')),shuffle:f.has('shuffle')};save();toast('学习设置已保存。');}});
document.addEventListener('keydown',e=>{if(view!=='study'||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)||!state.session||state.session.index>=state.session.queue.length)return;if(e.code==='Space'&&state.session.mode==='cards'){e.preventDefault();revealed=true;render();}if(['1','2','3'].includes(e.key)&&revealed&&state.session.mode==='cards'){record({'1':'again','2':'hard','3':'good'}[e.key]);next();}if(['1','2','3'].includes(e.key)&&state.session.mode==='choice'&&!feedback){const option=choiceQuestion?.options[Number(e.key)-1];if(option){const w=byId.get(state.session.queue[state.session.index]);feedback={correct:option.id===w.id,choice:option.id};render();$('#choice-next')?.focus();return;}}if(e.key.toLowerCase()==='p')speak(state.session.queue[state.session.index]);if(e.key==='Enter'&&feedback){record(feedback.correct?'good':'again');next();}});
$('#star-close').onclick=()=>$('#star-dialog').close();
$('#star-continue').onclick=()=>$('#star-dialog').close();
$('#star-repo').onclick=()=>$('#star-dialog').close();
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&e.newValue){try{state=validateState(JSON.parse(e.newValue),new Set(byId.keys()));revealed=false;feedback=null;render();toast('已载入另一个标签页保存的进度。');}catch{toast('另一标签页的进度无法读取，请导出备份后刷新。');}}});
async function init(){try{const res=await fetch('data/vocabulary.json');if(!res.ok)throw Error('词库加载失败');data=await res.json();words=data.words;byId=new Map(words.map(w=>[w.id,w]));years=[...new Set(words.map(w=>w.year))].sort();state=emptyState();try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)state=validateState(JSON.parse(raw),new Set(byId.keys()));}catch{saved=false;saveError='无法读取原有进度，请检查浏览器存储设置。';}render();maybeStarPrompt();}catch{$('#app').innerHTML='<div class="empty"><h1>词库暂时没有打开</h1><p>请检查网络连接后刷新页面。</p><button onclick="location.reload()">重新加载</button></div>';}}
init();
