import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import{DAY,schedule,statusOf,emptyState,validateState,makeQueue,normalizeAnswer,dateKey}from '../core.js';
test('spaced review grows and a forgotten word returns in ten minutes',()=>{let p=schedule(null,'good',1000);assert.equal(p.due,1000+DAY);p=schedule(p,'good',2000);assert.equal(p.interval,3);p=schedule(p,'good',3000);assert.equal(p.interval,7);p=schedule(p,'again',4000);assert.equal(p.due,604000);assert.equal(p.reps,0);assert.equal(p.lapses,1);assert.equal(statusOf(p,604000),'due');});
test('queue prioritizes due words and respects year, size and favorite filters',()=>{const ws=[{id:'a',year:2010},{id:'b',year:2010},{id:'c',year:2011},{id:'d',year:2010}];const s=emptyState();s.settings.shuffle=false;s.settings.batch=2;s.progress.b=schedule(null,'good',0);s.progress.d=schedule(null,'good',10*DAY);s.favorites=['c'];assert.deepEqual(makeQueue(ws,s,{year:'2010',now:2*DAY}),['b','a']);assert.deepEqual(makeQueue(ws,s,{kind:'due',now:2*DAY}),['b']);assert.deepEqual(makeQueue(ws,s,{kind:'favorites',now:2*DAY}),['c']);});
test('backup roundtrip preserves records and rejects corrupt input before import',()=>{const s=emptyState();s.progress.a=schedule(null,'hard',100);s.favorites=['a'];s.history['2026-10-01']={reviews:1,correct:0,ids:['a']};s.session={queue:['a'],index:0,year:'2010',mode:'spell',correct:0,answered:0};const restored=validateState(JSON.parse(JSON.stringify(s)),new Set(['a']));assert.deepEqual(restored,s);assert.throws(()=>validateState({...s,progress:{a:{due:'never'}}},new Set(['a'])));assert.throws(()=>validateState({...s,history:{'2026-10-01':{reviews:1,correct:2,ids:[]}}},new Set(['a'])));});
test('old duplicate IDs keep their progress and favorites after proofreading',()=>{const s=emptyState();const old='978bbb7dbb0856f7',current='02845dd3e44eb5ce';s.progress[old]=schedule(null,'good',100);s.favorites=[old];s.history['2026-10-01']={reviews:1,correct:1,ids:[old]};s.session={queue:[old],index:0,year:'2014',mode:'cards',correct:0,answered:0};const restored=validateState(s,new Set([current]));assert.deepEqual(restored.progress[current],s.progress[old]);assert.deepEqual(restored.favorites,[current]);assert.deepEqual(restored.history['2026-10-01'].ids,[current]);assert.deepEqual(restored.session.queue,[current]);});
test('spelling normalization supports punctuation and phrases without weakening spelling',()=>{assert.equal(normalizeAnswer(' Be  based on '),'be based on');assert.equal(normalizeAnswer('someone’s'),"someone's");assert.notEqual(normalizeAnswer('light'),normalizeAnswer('right'));});
test('date keys use local calendar date',()=>{assert.equal(dateKey(new Date(2026,9,1,0,2)),'2026-10-01');});
test('all vocabulary entries have valid years, definitions, stable unique IDs and source images',()=>{const d=JSON.parse(fs.readFileSync(new URL('../data/vocabulary.json',import.meta.url)));assert.equal(d.pages.length,75);assert.equal(new Set(d.words.map(w=>w.id)).size,d.words.length);assert.deepEqual([...new Set(d.words.map(w=>w.year))].sort(),Array.from({length:17},(_,i)=>2010+i));for(const w of d.words){assert.ok(w.word.length>1,w.word);assert.match(w.meaning,/[\u4e00-\u9fff]/);assert.ok(w.sources.length);for(const s of w.sources){const p=d.pages.find(p=>p.page===s.page);assert.ok(p);assert.ok(fs.existsSync(new URL('../'+p.image,import.meta.url)));}}});
